import React, { Suspense, useRef } from "react";
import Head from "next/head";

import { Canvas } from "@react-three/fiber";
import { OrbitControls, Plane } from "@react-three/drei";
import { Model } from "../components/Model";
import Gallery from "../components/Gallery";

export default function Home() {
  const ref = useRef();

  return (
    <>
      <Head>
        <title>David Martinez 3D Renders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col gap-15 h-screen">
        <div className="mt-20 h-screen">
          <div className="flex-1 flex-nowrap">
            <h1 className="text-center text-3xl font-bold uppercase pb-10">
              David Martinez 3D Renders
            </h1>
          </div>
          <div className="mb-40">
            <Gallery className="" />
          </div>

          <Canvas
            className="w-screen h-screen"
            id="canvas"
            camera={{ fov: 13, near: 5, far: 100, position: [0, 4, 7] }}
          >
            <ambientLight intensity={4} />
            <directionalLight
              color="white"
              position={[0, 4, 15]}
              intensity={4}
            />
            <directionalLight
              color="blue"
              intensity={0.1}
              position={[0, 4, 15]}
            />
            <pointLight
              color={"#f5fbca"}
              intensity={1}
              position={[144, 55, 20]}
            />

            <Suspense fallback={null}>
              <Model />
            </Suspense>
            <OrbitControls makeDefault ref={ref} autoRotate />
          </Canvas>
        </div>
      </main>
    </>
  );
}
